name: Speak to AKS

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: "dank_resources2"
  CLUSTER_NAME: "aks-dank_prime"

jobs:
  kubetime:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    # Checks out the repository this file is in
    - uses: actions/checkout@v3
    
    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v2.0
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}  
        
    - name: Install Kubelogin
      run: |
        curl -L $(curl -s https://api.github.com/repos/Azure/kubelogin/releases/latest \
          | jq -r ".assets[] | select(.name | test(\"linux-amd64.zip$\")) | .browser_download_url") \
          -o kubelogin.zip
        unzip kubelogin.zip
        chmod +x bin/linux_amd64/kubelogin
        echo "$(find "$(pwd)" -name kubelogin | rev | cut -d '/' -f 2- | rev)" >> $GITHUB_PATH
        
    - name: kubectl stuff
      run: |
        kubelogin convert-kubeconfig -l azurecli
        kubectl get nodes
